### ISSUE TITLE
Python: ThoroughDemo generated output does not flake

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#10]
Flake8 issues:
- Tabs instead of spaces (See issue #1)
- Many lines too wide (See issue #9)
- Need two newlines between leading comments and `class` definition.
- Valid python "skip" is to make the method body say `pass`, i.e.

```
def main():
    pass
```
- No imports present for superclasses, so they are undefined.
- Lines with no content should have no leading spaces (like line 8 in the ThoroughDemo example)

**Comment by orokro** [comment]
- Fixed
- Might take a while before I fix this, but I'll handle it in #9 
- Fixed. Added two newlines. Is this really a requirement of python?
- In this case I'm gonna leave python as pseudo code, because I dont want users to mistake "pass" as a required part of the class definition. It's should be obvious on it's own that # ... means code should go here.
- Not sure I want to implement imports / includes, as it's not strictly part of the class definition and more of part of the inner works of each language.
- Not sure what you mean for this one. When I copy the code into an editor empty lines have no characters. And line 8 is a comment that does have content...

**Comment by medthehatta** [comment]
Line 8 has spaces.  The editor may not be showing that they're there, but the spaces are there.

Trailing spaces are caught by flake because they can be confusing with version control: lines that are listed as changed may have only had invisible whitespace changes.

**Comment by orokro** [comment]
If you're not counting the comment on top:
![image](https://cloud.githubusercontent.com/assets/13468611/9985941/2bfaf6a2-5fea-11e5-91d8-0a791bdb4aac.png)

And if you are:
![image](https://cloud.githubusercontent.com/assets/13468611/9985945/404ed812-5fea-11e5-8d1d-5738016a18f5.png)

I dont line 8 isn't specific enough

**Comment by orokro** [comment]
![image](https://cloud.githubusercontent.com/assets/13468611/9985954/6f5d861c-5fea-11e5-9b91-81f8d026e77a.png)

Looks like line 5 inside the comment has a extra tab, but that's about it...

**Comment by medthehatta** [comment]
Ah, ok.  Yeah, that's the one then.
